### ISSUE TITLE
When building need to give --pull flag, 

### ISSUE THREAD

**Issue by bucknerns** [asashiho/ml-jupyter-python3#1]
Seeing this issue when using this image and trying to install something.
https://github.com/tianon/docker-brew-debian/issues/31
Rebuilding the image worked after adding swig dependency.

**Comment by bucknerns** [comment]
Turns out this was a docker issue not an image issue so closing this.

**Comment by asashiho** [comment]
Thank you & Sorry for replying so late 🙇‍♀️ 
I made some changes 😊😊😊 Would you be able to check them?

**Comment by bucknerns** [comment]
Works for me.

**Comment by asashiho** [comment]
Thank you 💟
